version: "3.7"
services:
  # dev-container
  dev:
    build:
      context: ./
    command: tail -f /dev/null
    network_mode: host
    volumes:
      - ../:/workdir/
      - .eslintrc.json:/workdir/.eslintrc.json
    working_dir: /workdir

